[fellowships]
display = "Fellowships & Scholarships"

[fellowships.bellon_qif]
honoree="Alex Bellon"
year="2024"
display="Qualcomm Innovation Fellowship"
display-extra="joint with Tess Despres"
money="$50,000"

[fellowships.switzer_google]
honoree="Jennifer Switzer"
year="2023"
display="Google PhD Fellowship"
#money="$35,000 annually, plus tuition"
money="$105,000 plus tuition"

[fellowships.yen_grfp]
honoree="Alex Yen"
year="2022"
display="National Science Foundation Graduate Research Fellowship (NSF GRFP)"
money="$111,000 plus tuition"

[fellowships.quiroga_trels]
honoree="Anthony Quiroga"
year="2021"
display="UC San Diego Triton Research & Experiential Learning Scholars (TRELS) Summar Scholarship"
money="$5,000"

[fellowships.marcano_sloan]
honoree="Gabriel Marcano"
year=2020
display="Sloan Scholar"
money="$40,000"

[fellowships.qif]
year=2013
display="Qualcomm Innovation Fellowship"
display-extra="(Honorable Mention), joint with Bradford Campbell"
money="$50,000"

[fellowships.ndseg]
year=2013
display="National Defense Science & Engineering Graduate Fellowship (NDSEG)"
money="$95,000 plus tuition"

[fellowships.grfp]
year=2013
display="National Science Foundation Graduate Research Fellowship (NSF GRFP)"
money="$90,000 plus tuition"

[fellowships.umichdept]
year=2012
display="University of Michigan Department of Computer Science First-Year Fellowship"



[publications]
display="Publication & Presentation Awards"

[publications.asplos2023]
year="2023"
display="Distinguished Paper Award, Proceedings of the 28th ACM International Conference on Architectural Support for Programming Languages and Operating Systems, Volume 2"

[publications.yen_cpsiotbench]
honoree="Alex Yen"
year="2021"
display="Best Presentation (Runner-Up), The 4th Workshop on Benchmarking Cyber-Physical Systems and Internet of Things (CPS-IoTBench)"

[publications.jagtap_enssys]
honoree="Dhananjay Jagtap"
year="2020"
display="Best Presentation (Second Prize), The 8th International Workshop on Energy Harvesting & Energy-Neutral Sensing Systems"

[publications.ipsn2018]
year=2018
display="Best Paper Finalist, The 17th ACM/IEEE International Conference on Information Processing in Sensor Networks"

[publications.terraswarm2017]
year=2017
display="David Wessel Best Demo Award, TerraSwarm Annual Review"

[publications.micro2016]
year=2016
display="IEEE Micro Top Pick in Computer Architecture"

[publications.inc2016]
year=2016
display="Outstanding Poster Award, Twelfth International Nanotechnology Conference on Communication and Cooperation"

[publications.hotwireless2015]
year=2015
display="Potential for Test of Time 2025 Award, The 2nd ACM Workshop on Hot Topics in Wireless"



[teaching]
display="Teaching & Mentoring Honors"

[teaching.ucsdcse2023]
year=2023
display="Outstanding Graduate Student Mentoring, Department of Computer Science and Engineering, University of California, San Diego"

[teaching.rackham2017]
year=2017
display="University of Michigan Rackham Graduate School Outstanding Graduate Student Instructor"

[teaching.umcoe2017]
year=2017
display="University of Michigan College of Engineering Richard & Eleanor Towner Prize for Outstanding Graduate Student Instructors"

[teaching.eecs2012]
year=2012
display="Best Undergraduate Instructor, University of Michigan, EECS"
