display="Teaching Experience"

[ucsd.sp23-291]
term = ["2023 Spring"]
role = "Primary Instructor"
dept = "CSE"
number = "291"
title = "Critical Analysis in Computing"
extra-md = """
This course is the product of our cohort's participation in the
[Cultural Competence in Computing (3C) Fellowship Program](https://identity.cs.duke.edu/fellows.html).

This course aims to introduce computer scientists and engineers to the
principles of critical analysis and to teach them how to apply critical
analysis to current and emerging technologies.
The intended audience of this course is graduate or senior students who have
deep technical knowledge, but more limited experience reasoning about human and
societal factors. This course aims to be a bridge, presenting an accelerated
introduction to contemporary social science and critical analysis in a manner
familiar to engineering scholars.

Course website: [sites.google.com/ucsd.edu/sp23-cse291-critical-computing/](https://sites.google.com/ucsd.edu/sp23-cse291-critical-computing/)"""


[ucsd.240a]
term = ["2023 Winter"]
role = "Primary Instructor"
dept = "CSE"
number = "240A"
title = "Principles in Computer Architecture"

[ucsd.wes237b]
term = ["2022 Summer", "2023 Summer"]
role = "Primary Instructor"
dept = "WES"
number = "237B"
title = "Introductions to Embedded Systems Design"

[ucsd.wxiot]
term = ["2022 Winter", "2022 Fall", "2023 Winter"]
role = "Primary Instructor"
dept = "CSE/WES"
number = "{122/190/222C/291}/269"
title = "Wireless and Communication in the Internet of Things"
extra-md = """
This course is the subject of
[our 2024 SIGCSE paper](https://dl.acm.org/doi/10.1145/3626252.3630848).

This class focuses on how a system designer should choose and use the wide
array of wireless technologies. Specifically, we look at WiFi, Classic
Bluetooth, Bluetooth Low Energy, IEEE 802.15.4, 2g/3g/4g/5g cellular, LTE-M,
NB-IoT, LoRa, SigFox, and some time with more esoteric choices, such as Visible
Light Communication (VLC), Infrared Communication (IR), Ultrasonic, and
boutique RF such as wake-up radios and backscatter. Persons finishing this
course should be well-suited for work in real-world IoT systems upon
completion.

Materials for lectures, labs, and projects are open and available for quarter
system, semester system, and professional masters versions of this course.
"""

[ucsd.141l]
term = ["2022 Winter"]
role = "Primary Instructor"
dept = "CSE"
number = "141L"
title = "Introduction to Computer Architecture Lab"

[ucsd.141]
term = ["2020 Fall", "2022 Spring", "2023 Fall"]
role = "Primary Instructor"
dept = "CSE"
number = "141"
title = "Introduction to Computer Architecture"

[ucsd.290]
term = ["2020 Fall"]
role = "Primary Instructor"
dept = "CSE"
number = "290"
title = "Seminar on Topics in Embedded Systems"
url = "https://sites.google.com/eng.ucsd.edu/embeddedlunch/"

[ucsd.wi20-291]
term = ["2020 Winter"]
role = "Primary Instructor"
dept = "CSE"
number = "291"
title = "Platforms & Systems to Bridge the Digital & Physical World"

[um.398]
term = ["2016 Fall", "2016 Winter"]
role = "Primary Instructor"
dept = "EECS"
number = "398"
title = "Computing for Computer Scientists"
extra-md = """
A new class designed and built from scratch.
This class attempts to address the experience gap that exists across the spectrum of incoming Computer Science students.
While driven by tools (shells, build systems, debuggers, version control), it explores how and why computer scientists interface with computers differently in their day-to-day activities, how to apply principles learned in courses to everyday activities, and ultimately how to be a more efficient user of computing resources.

This course has been adopted as part of the permanent curriculum at the University of Michigan as EECS 201: Computing Pragmatics, an advised co-requisite for first-year EECS majors.

[https://c4cs.github.io](https://c4cs.github.io)

_In 2017, I was awarded the Rackham Graduate School Outstanding Graduate Student Instructor and the College of Engineering Richard & Eleanor Towner Prize for Outstanding Graduate Student Instructors for this course._"""

[um.373grad]
term = ["2015 Fall", "2015 Winter"]
role = "Graduate Teaching Assistant"
dept = "EECS"
number = "373"
title = "Design of Microprocessor Based Systems"

[um.470]
term = ["2012 Winter", "2012 Fall"]
role = "Undergraduate Teaching Assistant"
dept = "EECS"
number = "470"
title = "Computer Architecture"

[um.482]
term = ["2012 Winter", "2011 Fall", "2011 Winter", "2010 Fall"]
role = "Undergraduate Teaching Assistant"
dept = "EECS"
number = "482"
title = "Introduction to Operating Systems"

[um.373ugrad]
term = ["2011 Fall", "2011 Winter"]
role = "Undergraduate Teaching Assistant"
dept = "EECS"
number = "373"
title = "Design of Microprocessor Based Systems"
